// --- UTILITIES ---

function copyReceipt() {
    const txt = `C9 Duty Check:\nReport: ${lastCalc.rTime} ${lastCalc.rAir} (${lastCalc.hdt} ${lastCalc.hb} Time)\nScheduled FLT Time: ${lastCalc.flt}\nMax Duty: ${lastCalc.max}\nHard Stop: ${lastCalc.hardStop}\nDeductions: ${lastCalc.deducts.join(', ')}\nLATEST DOOR CLOSE: ${lastCalc.final}\n(Generated by C9 Duty Max)`;
    const ta = document.getElementById('copyArea');
    ta.value = txt;
    ta.select();
    document.execCommand('copy');
    const btn = document.querySelector('#resultCard button i');
    btn.className = "fa-solid fa-check text-green-400";
    setTimeout(() => btn.className = "fa-regular fa-copy", 1500);
}

function toggleDarkMode() {
    document.body.classList.toggle('dark-mode');
    const icon = document.getElementById('darkModeIcon');
    const text = document.getElementById('darkModeText');
    const themeMeta = document.getElementById('themeColor');

    if (document.body.classList.contains('dark-mode')) {
        icon.classList.remove('fa-moon'); icon.classList.add('fa-sun');
        text.textContent = "Light Mode";
        themeMeta.content = "#1f2937";

    } else {
        icon.classList.remove('fa-sun'); icon.classList.add('fa-moon');
        text.textContent = "Dark Mode";
        themeMeta.content = "#002244";

    }
    validateAirport(document.getElementById('reportAirport'));
    validateAirport(document.getElementById('depAirport'));
}

function toggleMode() {
    const isDom = document.getElementById('modeDom').checked;
    const hvtCheck = document.getElementById('isHVT');
    const hvtCont = document.getElementById('hvtContainer');

    if (isDom) {
        hvtCheck.disabled = false;
        hvtCont.style.opacity = "1";
    } else {
        hvtCheck.disabled = true;
        hvtCheck.checked = false;
        hvtCont.style.opacity = "0.5";
    }
    resetResult();
}

function checkCoTerminal() {
    const hb = document.getElementById('homeBase').value;
    const container = document.getElementById('coTermContainer');
    const check = document.getElementById('isCoTerm');
    check.checked = false;
    toggleCoTermDropdown();
    if (CO_TERMS[hb]) {
        container.classList.remove('hidden');
    } else {
        container.classList.add('hidden');
    }
}

function toggleCoTermDropdown() {
    const isChecked = document.getElementById('isCoTerm').checked;
    const ddCont = document.getElementById('coTermDropdownContainer');
    const dd = document.getElementById('coTermSelect');
    const hb = document.getElementById('homeBase').value;
    dd.innerHTML = '<option value="0">Select Arrival Terminal...</option>';
    if (isChecked && CO_TERMS[hb]) {
        ddCont.classList.remove('hidden');
        Object.entries(CO_TERMS[hb]).forEach(([code, mins]) => {
            const opt = document.createElement('option');
            const h = Math.floor(mins / 60);
            const m = mins % 60;
            const dur = `${h}:${m.toString().padStart(2, '0')}`;
            opt.value = mins;
            opt.text = `${code} (Surface: ${dur})`;
            dd.appendChild(opt);
        });
    } else {
        ddCont.classList.add('hidden');
    }
}

function resetResult() {
    document.getElementById('resultCard').classList.add('hidden');
    document.getElementById('errorContainer').classList.add('hidden');
    const isDom = document.getElementById('modeDom').checked;
    const prefix = isDom ? "<b class='uppercase'>DOMESTIC</b>" : "<b class='uppercase'>INTERNATIONAL</b>";
    document.getElementById('liveCalcText').innerHTML = ""; // Clear initial text to avoid "ghost message" until calc is ready

}

function resetForm() {
    const d = new Date();
    const denverDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Denver', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
    document.getElementById('dutyDate').value = denverDate;
    document.getElementById('homeBase').value = 'DEN';
    ['reportAirport', 'reportTime', 'depAirport', 'flightTimeInput'].forEach(id => { const el = document.getElementById(id); el.value = ''; el.classList.remove('valid-airport', 'invalid-airport'); });
    document.querySelectorAll('.toggle-checkbox').forEach(el => { el.checked = false; el.nextElementSibling.classList.remove('active'); });
    ['repManualZone', 'depManualZone'].forEach(id => { const el = document.getElementById(id); el.classList.add('hidden'); el.value = ''; });

    ['rep', 'dep'].forEach(pfx => {
        const autoCont = document.getElementById(pfx + 'ZoneAutoContainer');
        const manCont = document.getElementById(pfx + 'ManualContainer');
        const autoInput = document.getElementById(pfx + 'ZoneAuto');
        if (autoCont && manCont) {
            autoCont.classList.remove('hidden');
            manCont.classList.add('hidden');
            autoInput.value = '--';
            autoInput.className = "info-field w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300";
            // Hide nudge buttons on reset
            const nWest = document.getElementById(pfx + 'NudgeWest');
            const nEast = document.getElementById(pfx + 'NudgeEast');
            if (nWest) nWest.classList.add('invisible');
            if (nEast) nEast.classList.add('invisible');
        }
    });

    // Explicitly reset the labels here
    const lblRep = document.getElementById('rtLabelCity');
    if (lblRep) { lblRep.textContent = "Local"; lblRep.className = ""; }


    document.getElementById('modeDom').click();
    checkCoTerminal();
    resetResult();
}

function getZone(c) { return ALL_CODES[c] ? (ZONES[ALL_CODES[c]] || ALL_CODES[c]) : null; }

function getZoneName(iana, manId) {
    if (!iana && manId) iana = document.getElementById(manId).value;
    if (!iana) return "Loc";
    try {
        const dtStr = document.getElementById('dutyDate').value;
        const dt = dtStr ? new Date(dtStr + 'T12:00:00') : new Date();
        const parts = new Intl.DateTimeFormat('en-US', { timeZone: iana, timeZoneName: 'short' }).formatToParts(dt);
        return parts.find(p => p.type === 'timeZoneName')?.value || "Loc";
    } catch (e) { return "Loc"; }
}

function padTimeInput(el) {
    let v = el.value.trim(); if (!v) return;
    v = v.replace(/\D/g, '');
    if (v.length > 2) { const i = v.length === 3 ? 1 : 2; v = v.slice(0, i) + ':' + v.slice(i); }
    const p = v.split(':');
    if (p.length === 2) el.value = `${p[0].padStart(2, '0')}:${p[1].padStart(2, '0')}`;
}

function formatTimeInput(el) {
    let v = el.value.replace(/\D/g, '');
    if (v.length > 4) v = v.slice(0, 4);
    if (v.length > 2) { const i = v.length === 3 ? 1 : 2; v = v.slice(0, i) + ':' + v.slice(i); }
    el.value = v;
}

function nudgeZone(pfx, dir) {
    const sel = document.getElementById(pfx + 'ManualZone');
    const count = sel.options.length;
    let idx = sel.selectedIndex;
    if (idx === 0) idx = 1;
    else idx += dir;
    if (idx < 1) idx = count - 1;
    if (idx >= count) idx = 1;
    sel.selectedIndex = idx;
    sel.onchange();
}

function validateAirport(el) {
    el.value = el.value.toUpperCase();
    const code = el.value;
    const pfx = el.id === 'reportAirport' ? 'rep' : 'dep';
    const zoneAutoCont = document.getElementById(pfx + 'ZoneAutoContainer');
    const zoneManualCont = document.getElementById(pfx + 'ManualContainer');
    const zoneAuto = document.getElementById(pfx + 'ZoneAuto');
    const nudgeWest = document.getElementById(pfx + 'NudgeWest');
    const nudgeEast = document.getElementById(pfx + 'NudgeEast');

    if (!zoneAutoCont || !zoneManualCont) return;
    const isDark = document.body.classList.contains('dark-mode');
    zoneAuto.style.pointerEvents = "none";

    if (code.length === 3) {
        if (ALL_CODES[code]) {
            el.classList.add('valid-airport');
            el.classList.remove('invalid-airport');

            // Dynamic Label Logic
            if (el.id === 'reportAirport') {
                const lbl = document.getElementById('rtLabelCity');
                if (lbl) { lbl.textContent = code; lbl.className = "dynamic-city-label font-bold"; }
            }

            const iana = getZone(code);
            const shortZone = getZoneName(iana);
            zoneAuto.value = shortZone;
            zoneAutoCont.classList.remove('hidden');
            zoneManualCont.classList.add('hidden');
            if (nudgeWest) nudgeWest.classList.add('invisible');
            if (nudgeEast) nudgeEast.classList.add('invisible');

            if (shortZone.includes('DT') || shortZone.includes('BST') || shortZone.includes('CEST') || shortZone.includes('EEST')) {
                zoneAuto.className = isDark ? "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-emerald-900/50 border border-emerald-700 text-emerald-200" : "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-emerald-100 border border-emerald-300 text-emerald-800";
            } else {
                zoneAuto.className = isDark ? "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-sky-900/50 border border-sky-700 text-sky-200" : "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-sky-100 border border-sky-300 text-sky-800";
            }
        } else {
            el.classList.remove('valid-airport');
            el.classList.add('invalid-airport');
            // Reset labels if invalid
            if (el.id === 'reportAirport') {
                const lbl = document.getElementById('rtLabelCity');
                if (lbl) { lbl.textContent = "Local"; lbl.className = ""; }
            }
            zoneAutoCont.classList.add('hidden');
            zoneManualCont.classList.remove('hidden');
            if (nudgeWest) nudgeWest.classList.remove('invisible');
            if (nudgeEast) nudgeEast.classList.remove('invisible');
        }
    } else {
        el.classList.remove('valid-airport', 'invalid-airport');
        // Reset labels if empty/partial
        if (el.id === 'reportAirport') {
            const lbl = document.getElementById('rtLabelCity');
            if (lbl) { lbl.textContent = "Local"; lbl.className = ""; }
        }
        zoneAuto.value = "--";
        zoneAutoCont.classList.remove('hidden');
        zoneManualCont.classList.add('hidden');
        if (nudgeWest) nudgeWest.classList.add('invisible');
        if (nudgeEast) nudgeEast.classList.add('invisible');
        zoneAuto.className = "info-field w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300";
    }
}

function updateAllLabels() {
    if (document.getElementById('reportAirport').value) validateAirport(document.getElementById('reportAirport'));
    if (document.getElementById('depAirport').value) validateAirport(document.getElementById('depAirport'));
}

function showInfo(k) {
    const title = document.getElementById('modalTitle');
    const text = document.getElementById('modalText');
    const modal = document.getElementById('infoModal');

    if (title && text && modal && INFO_CONTENT[k]) {
        title.textContent = INFO_CONTENT[k].title;
        text.innerHTML = INFO_CONTENT[k].text;
        modal.classList.remove('hidden');
    }
}
function closeInfo() { document.getElementById('infoModal').classList.add('hidden'); }

// --- NEW: Flight Time Warning Logic ---
let flightWarningDismissed = false;

function warnFlightTime() {
    const val = document.getElementById('flightTimeInput').value;
    const popup = document.getElementById('flightTimeWarning');
    if (!popup) return;

    if (val.length > 0 && !flightWarningDismissed) {
        popup.classList.remove('hidden');
    } else {
        popup.classList.add('hidden');
    }
}

function dismissFlightWarning() {
    const popup = document.getElementById('flightTimeWarning');
    if (popup) popup.classList.add('hidden');
    flightWarningDismissed = true;
}

// --- CORE CALCULATION LOGIC ---

function getDateInZone(dateStr, timeStr, ianaZone) {
    const cleanTime = timeStr.replace(':', '').padStart(4, '0');
    const h = cleanTime.slice(0, 2);
    const m = cleanTime.slice(2, 4);
    const inputYear = parseInt(dateStr.split('-')[0]);
    const inputMonth = parseInt(dateStr.split('-')[1]) - 1;
    const inputDay = parseInt(dateStr.split('-')[2]);
    const inputHour = parseInt(h);
    const inputMin = parseInt(m);
    let guess = Date.UTC(inputYear, inputMonth, inputDay, inputHour, inputMin);
    for (let i = 0; i < 3; i++) {
        const parts = new Intl.DateTimeFormat('en-US', { timeZone: ianaZone, year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: false }).formatToParts(guess);
        const getP = (t) => parseInt(parts.find(p => p.type === t).value);
        const gY = getP('year'); const gM = getP('month') - 1; const gD = getP('day'); const gH = getP('hour') === 24 ? 0 : getP('hour'); const gMin = getP('minute');
        const guessTimeInZone = Date.UTC(gY, gM, gD, gH, gMin);
        const actualTarget = Date.UTC(inputYear, inputMonth, inputDay, inputHour, inputMin);
        const diff = actualTarget - guessTimeInZone;
        if (diff === 0) break;
        guess += diff;
    }
    return guess;
}

function getDynamicZoneName(utcTime, ianaZone) {
    try {
        const parts = new Intl.DateTimeFormat('en-US', { timeZone: ianaZone, timeZoneName: 'short' }).formatToParts(new Date(utcTime));
        return parts.find(p => p.type === 'timeZoneName')?.value || "Loc";
    } catch (e) { return "Loc"; }
}



let lastCalc = {};

function calculateDuty() {
    const errCont = document.getElementById('errorContainer'), errMsg = document.getElementById('errorMsg'); errCont.classList.add('hidden');

    // --- NEW: Reset Error Classes Before Checking ---
    ['dutyDate', 'homeBase', 'reportAirport', 'reportTime', 'depAirport', 'flightTimeInput'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.classList.remove('input-missing');
    });

    const req = [{ id: 'dutyDate', n: 'Duty Date' }, { id: 'homeBase', n: 'Home Base' }, { id: 'reportAirport', n: 'Report City' }, { id: 'reportTime', n: 'Report Time' }, { id: 'depAirport', n: 'Dep City' }, { id: 'flightTimeInput', n: 'Flight Time' }];

    let hasError = false;
    let firstMissing = null;

    // --- NEW: Loop to highlight ALL missing fields ---
    for (let r of req) {
        const el = document.getElementById(r.id);
        if (!el.value) {
            el.classList.add('input-missing');
            if (!firstMissing) firstMissing = r.n;
            hasError = true;
        }
    }

    if (hasError) {
        errMsg.textContent = `Missing: ${firstMissing}`;
        errCont.classList.remove('hidden');
        return;
    }

    // ... rest of logic

    const hb = document.getElementById('homeBase').value;
    const rTimeStr = document.getElementById('reportTime').value;
    let rAir = document.getElementById('reportAirport').value.toUpperCase();
    let dAir = document.getElementById('depAirport').value.toUpperCase();
    const dateStr = document.getElementById('dutyDate').value;
    const isDom = document.getElementById('modeDom').checked;

    if (rAir !== 'ZZZ') {
        if (!ALL_CODES[rAir] && document.getElementById('repManualZone').value === "") { errMsg.textContent = "Invalid Report City: Select Zone"; errCont.classList.remove('hidden'); return; }
    }
    if (!ALL_CODES[dAir] && document.getElementById('depManualZone').value === "") { errMsg.textContent = "Invalid Dep City: Select Zone"; errCont.classList.remove('hidden'); return; }

    let rZone;
    if (rAir === 'ZZZ') { rZone = getZone('DEN'); } else { rZone = ALL_CODES[rAir] ? getZone(rAir) : document.getElementById('repManualZone').value; }
    const dZone = ALL_CODES[dAir] ? getZone(dAir) : document.getElementById('depManualZone').value;
    const hZone = getZone(hb);

    const reportUTC = getDateInZone(dateStr, rTimeStr, rZone);
    const rZnStr = getDynamicZoneName(reportUTC, rZone);
    const hdtParts = new Intl.DateTimeFormat('en-US', { timeZone: hZone, hour: 'numeric', minute: 'numeric', hour12: false }).formatToParts(reportUTC);
    const hH = parseInt(hdtParts.find(p => p.type === 'hour').value) % 24; const hM = parseInt(hdtParts.find(p => p.type === 'minute').value);
    const hdtMins = hH * 60 + hM;
    const hZnStr = getDynamicZoneName(reportUTC, hZone);

    const fStr = document.getElementById('flightTimeInput').value.replace(':', '').padStart(4, '0'); const fH = parseInt(fStr.slice(0, 2)) || 0, fM = parseInt(fStr.slice(2, 4)) || 0;
    const schedFlightMins = fH * 60 + fM;
    let maxDutyMins = 0; let expl = ""; const fmt = (m) => { let h = Math.floor(m / 60), mn = m % 60; return `${h.toString().padStart(2, '0')}:${mn.toString().padStart(2, '0')}`; }

    if (isDom) {
        const isHVT = document.getElementById('isHVT').checked; const isDay = hdtMins >= 300 && hdtMins <= 1139; let limit = 13;
        expl = `13hrs (Report ${fmt(hdtMins)} HDT, 1900-0459)`;
        if (isHVT) {
            limit = 16;
            expl = `16hrs (HVT)`;
        } else {
            if (isDay) { limit = 15; expl = `15hrs (Report ${fmt(hdtMins)} HDT, 0500-1859)`; }
        }
        maxDutyMins = limit * 60;
    } else {
        if (schedFlightMins <= 480) { maxDutyMins = 16 * 60; expl = "16:00 (Int'l, Flt ≤ 8:00)"; }
        else if (schedFlightMins <= 720) { maxDutyMins = 16 * 60 + 30; expl = "16:30 (Int'l, Flt 8:01-12:00)"; }
        else { const checkIn = 75; const buffer = 210; maxDutyMins = checkIn + schedFlightMins + buffer; const debrief = document.getElementById('isDHD').checked ? 0 : 15; let cust = 0; if (document.getElementById('customsStart').checked) cust += 15; if (document.getElementById('customsEnd').checked) cust += 15; maxDutyMins += (debrief + cust); expl = "Variable (Check-in + Flt + Cust + Debr + 3:30)"; }
    }

    const debrief = document.getElementById('isDHD').checked ? 0 : 15;
    let cust = 0; if (document.getElementById('customsStart').checked) cust += 15; if (document.getElementById('customsEnd').checked) cust += 15;
    let coTermDed = 0; const isCoTerm = document.getElementById('isCoTerm').checked; if (isCoTerm && !document.getElementById('coTermContainer').classList.contains('hidden')) { coTermDed = parseInt(document.getElementById('coTermSelect').value) || 0; }
    const flightMs = schedFlightMins * 60000;
    const deductionsMs = (debrief + cust + coTermDed) * 60000;
    const maxDutyMs = maxDutyMins * 60000;
    const hardStopUTC = reportUTC + maxDutyMs;
    const doorCloseUTC = hardStopUTC - deductionsMs - flightMs;

    const timeInZone = (utc, z) => { const f = new Intl.DateTimeFormat('en-US', { timeZone: z, hour: 'numeric', minute: 'numeric', hour12: false }); const p = f.formatToParts(utc); const h = p.find(x => x.type === 'hour').value.padStart(2, '0'); const m = p.find(x => x.type === 'minute').value.padStart(2, '0'); return `${h}:${m}`; };

    const dZnStr = getDynamicZoneName(doorCloseUTC, dZone);
    const stopZnStr = getDynamicZoneName(hardStopUTC, dZone);
    const repInDepZn = getDynamicZoneName(reportUTC, dZone);
    const doorCloseStr = timeInZone(doorCloseUTC, dZone);

    document.getElementById('resultTime').textContent = doorCloseStr;
    document.getElementById('resultZone').textContent = `${dAir} Time (${dZnStr})`;

    document.getElementById('calcStepReportLocal').textContent = `${rTimeStr.replace(/(\d{2})(\d{2})/, '$1:$2')} ${rAir} (${rZnStr})`;
    document.getElementById('calcStepReportHDT').textContent = `${timeInZone(reportUTC, hZone)} ${hb} (${hZnStr})`;

    const repInDep = timeInZone(reportUTC, dZone);
    document.getElementById('calcStepReportDep').textContent = `${repInDep} ${dAir} (${repInDepZn})`;
    document.getElementById('calcStepMax').textContent = `+${fmt(maxDutyMins)}`;
    document.getElementById('calcStepMaxExplanation').textContent = expl;

    const stopLabel = document.getElementById('calcStepStopLabel');
    if (repInDepZn !== stopZnStr) {
        stopLabel.textContent = "= Duty Hard Stop (DST Adj.)";
    } else {
        stopLabel.textContent = "= Duty Hard Stop";
    }
    document.getElementById('calcStepStop').textContent = `${timeInZone(hardStopUTC, dZone)} ${dAir} (${stopZnStr})`;

    const rowCT = document.getElementById('rowCoTermLabel');
    const rowCTVal = document.getElementById('valCoTerm');
    if (coTermDed > 0) { rowCT.classList.remove('hidden'); rowCTVal.classList.remove('hidden'); rowCTVal.textContent = `-${coTermDed}`; } else { rowCT.classList.add('hidden'); rowCTVal.classList.add('hidden'); }

    document.getElementById('calcStepDebriefLabel').textContent = debrief === 0 ? "- Debrief (DHD)" : "- Debrief"; document.getElementById('calcStepDebriefVal').textContent = `-${debrief}`;

    const crL = document.getElementById('calcStepCustomsRowLabel');
    const crV = document.getElementById('calcStepCustoms');
    if (cust > 0) { crL.classList.remove('hidden'); crV.classList.remove('hidden'); crV.textContent = `-${cust}`; } else { crL.classList.add('hidden'); crV.classList.add('hidden'); }

    document.getElementById('calcStepFlight').textContent = `-${fH}:${fM.toString().padStart(2, '0')}`;
    document.getElementById('calcStepResult').textContent = `${doorCloseStr} ${dAir} (${dZnStr})`;

    const rc = document.getElementById('resultCard'); rc.classList.remove('hidden'); rc.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

    lastCalc = {
        rTime: rTimeStr.replace(/(\d{2})(\d{2})/, '$1:$2'),
        rAir: rAir, hdt: `${fmt(hdtMins)}`, hb: hb,
        flt: `${fH}:${fM.toString().padStart(2, '0')}`,
        max: expl, hardStop: `${timeInZone(hardStopUTC, dZone)} ${dAir}`,
        deducts: [],
        final: `${doorCloseStr} ${dAir}`
    };
    if (debrief > 0) lastCalc.deducts.push(`Debrief ${debrief}m`);
    if (cust > 0) lastCalc.deducts.push(`Customs ${cust}m`);
    if (coTermDed > 0) lastCalc.deducts.push(`Co-Term Travel ${coTermDed}m`);
    if (lastCalc.deducts.length === 0) lastCalc.deducts.push("None");
}

/* =========================================
   OCR / SCAN FEATURE LOGIC
   ========================================= */

// --- STATE ---
let parsedFlights = [];
const ORIGIN_MAP = {
    'A': 'AUS', 'B': 'BOS', 'V': 'CLE', 'D': 'DEN', 'E': 'EWR',
    'R': 'FLL', 'G': 'GUM', 'N': 'HNL', 'W': 'IAD', 'H': 'IAH',
    '6': 'LAS', 'L': 'LAX', 'U': 'LHR', '5': 'MCO', 'O': 'ORD',
    '3': 'PHX', '4': 'SAN', 'F': 'SFO', 'T': 'TPA'
};

// --- DOM ACTIONS ---
function openScanModal() {
    document.getElementById('scanModal').classList.remove('hidden');
    // Check if Protocol is file:
    if (window.location.protocol === 'file:') {
        showScanError("Note: OCR requires a local server or HTTPS. It may fail if opened directly from a file.");
    }
}
function closeScanModal() {
    document.getElementById('scanModal').classList.add('hidden');
    document.getElementById('pairingFile').value = '';
    document.getElementById('scanPreview').classList.add('hidden');
    document.getElementById('scanPlaceholder').classList.remove('hidden');
    document.getElementById('scanStatus').classList.add('hidden');
    document.getElementById('scanErrorMsg').classList.add('hidden');
}

function showScanError(msg) {
    const el = document.getElementById('scanErrorMsg');
    el.textContent = msg;
    el.classList.remove('hidden');
    document.getElementById('scanStatus').classList.add('hidden');
}

function handleFileSelect(input) {
    if (input.files && input.files[0]) {
        const file = input.files[0];
        // Show Preview
        const reader = new FileReader();
        reader.onload = function (e) {
            const preview = document.getElementById('scanPreview');
            preview.src = e.target.result;
            preview.classList.remove('hidden');
            document.getElementById('scanPlaceholder').classList.add('hidden');

            // Start OCR
            runOCR(file);
        };
        reader.readAsDataURL(file);
    }
}

// --- OCR ENGINE ---
async function runOCR(file) {
    const statusDiv = document.getElementById('scanStatus');
    const statusText = document.getElementById('scanStatusText');
    statusDiv.classList.remove('hidden');
    document.getElementById('scanErrorMsg').classList.add('hidden'); // Clear prev errors
    statusText.textContent = "Initializing Engine...";

    if (typeof Tesseract === 'undefined') {
        showScanError("Tesseract JS not loaded. Check internet connection.");
        return;
    }

    try {
        const worker = await Tesseract.createWorker('eng', 1, {
            logger: m => {
                if (m.status === 'recognizing text') {
                    statusText.textContent = `Scanning... ${Math.round(m.progress * 100)}%`;
                }
            }
        });

        statusText.textContent = "Processing Text...";
        const ret = await worker.recognize(file);
        await worker.terminate();

        processOCRText(ret.data.text);

    } catch (e) {
        console.error(e);
        showScanError("OCR Failed. " + e.message);
    }
}

// --- AUTO-MODE LOGIC ---
const DOMESTIC_ZONES = ['E', 'C', 'M', 'P', 'H', 'AK', 'AZ', 'ATL', 'YHZ', 'NFLD', 'MXC', 'MXE', 'MXM', 'MXS', 'PVR'];

function autoSelectMode(dep, arr) {
    if (dep === "???" || arr === "???") return; // Can't determine

    const getZ = (a) => ALL_CODES[a] ? (ZONES[ALL_CODES[a]] || ALL_CODES[a]) : null;

    // Helper to check if a zone key (like 'E' or 'LHR') is Domestic
    const isDom = (airport) => {
        const zKey = ALL_CODES[airport];
        if (!zKey) return true; // Default to Dom if unknown? Or keep current.
        // If zKey is in DOMESTIC_ZONES, it's Dom.
        return DOMESTIC_ZONES.includes(zKey);
    };

    const depDom = isDom(dep);
    const arrDom = isDom(arr);

    // If ANY flight in the duty is International, the matching mode applies.
    // Definition: "International Flying includes flying to and from..."
    // So if Dep OR Arr is Int'l -> Mode International.
    if (!depDom || !arrDom) {
        document.getElementById('modeInt').click();
    } else {
        document.getElementById('modeDom').click();
    }
}

// --- PARSING & VETTING ---
function processOCRText(text) {
    // 1. VETTING: Check for "Updated" signals
    const updatedMatches = (text.match(/\d{2}:\d{2}A/g) || []).length;
    if (updatedMatches > 2) {
        showScanError("UPDATED PAIRING DETECTED. Please stick to the SCHEDULED view (without 'A' flags) for accuracy.");
        return;
    }

    // 2. EXTRACTION
    const pairingMatch = text.match(/Pairing\s*[#:]*\s*([A-Z0-9]+)/i) || text.match(/([D|F|S|L|E|I|H|O][A-Z0-9]{3,4})/);
    let pairingId = "---";
    let homeBase = "DEN";
    if (pairingMatch) {
        pairingId = pairingMatch[1];
        const firstChar = pairingId.charAt(0).toUpperCase();
        if (ORIGIN_MAP[firstChar]) homeBase = ORIGIN_MAP[firstChar];
    }

    // 3. FLIGHT PARSING
    const lines = text.split('\n');
    let flights = [];
    let currentDutyDate = "";
    let currentReportTime = "";

    // Iterate lines with look-ahead/context
    for (let i = 0; i < lines.length; i++) {
        let line = lines[i].trim();

        // A. DATE Parsing
        const dateMatch = line.match(/DP\s*\d+\s*(\d{1,2}\/\d{1,2}\/\d{2})/);
        if (dateMatch) {
            currentDutyDate = dateMatch[1];
            currentReportTime = "";
        }

        // B. REPORT TIME Parsing
        if (line.match(/Report/i) || line.match(/Check-In/i)) {
            let rTime = line.match(/(\d{2}[:.]\d{2})/);
            if (rTime) {
                currentReportTime = rTime[1].replace('.', ':');
            } else {
                if (i + 1 < lines.length) {
                    const nextLine = lines[i + 1];
                    const nextTime = nextLine.match(/(\d{2}[:.]\d{2})/);
                    if (nextTime) {
                        currentReportTime = nextTime[1].replace('.', ':');
                    }
                }
            }
        }

        // C. FLIGHT Parsing
        if ((line.includes("UA") || line.includes("United")) && (line.match(/\s\d{3,4}\s/) || line.match(/Flight/i))) {
            try {
                const fltMatch = line.match(/(?:UA|United)\s*(\d{3,4})/i);
                if (!fltMatch) continue;
                const fltNum = fltMatch[1];

                // Regex to find HH:MM or HH.MM style times
                const times = line.match(/(\d{2}[:.]\d{2})/g);
                let depTime = times && times.length > 0 ? times[0].replace('.', ':') : "";
                let arrTime = times && times.length > 1 ? times[1].replace('.', ':') : "";
                // Capture Block Time (usually 3rd time in the row: Dep, Arr, Block)
                let blockTime = times && times.length > 2 ? times[2].replace('.', ':') : "";

                let depAir = "???";
                let arrAir = "???";

                const findAirports = (str) => {
                    const caps = str.match(/[A-Z]{3}/g);
                    if (!caps) return null;
                    const NOISE = ['ARR', 'DEP', 'FLT', 'SKD', 'ACT', 'BLK', 'GRD', 'EQP', 'DHD', 'LAY', 'OUT', 'OFF', 'ON', 'IN', 'SAT', 'SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'POS'];
                    return caps.filter(c => !NOISE.includes(c) && !c.includes('DP'));
                };

                let airCands = findAirports(line);
                if ((!airCands || airCands.length < 2) && (i + 1 < lines.length)) {
                    const nextLine = lines[i + 1];
                    const nextCands = findAirports(nextLine);
                    if (nextCands && nextCands.length >= 2) {
                        airCands = nextCands;
                    }
                }

                if (airCands && airCands.length >= 2) {
                    depAir = airCands[0];
                    arrAir = airCands[1];
                }

                flights.push({
                    date: currentDutyDate || "Unknown",
                    reportTime: currentReportTime,
                    flt: fltNum,
                    depTime: depTime,
                    arrTime: arrTime,
                    depAir: depAir,
                    arrAir: arrAir,
                    blockTime: blockTime, // Store captured block time
                    homeBase: homeBase
                });

            } catch (e) { console.warn("Parse error", e); }
        }
    }

    if (flights.length === 0) {
        showScanError("No flights found. Ensure image is clear and contains 'UA' flight numbers.");
        return;
    }

    // Success -> Show Selection Modal
    closeScanModal();
    window.parsedFlights = flights; // Explicit global assignment
    window.lastOcrText = text;
    renderFlightSelection(flights, pairingId);
}

function showRawOcr() {
    const t = window.lastOcrText || "No OCR text found.";
    const ta = document.getElementById('copyArea');
    ta.value = t;
    ta.select();
    try { document.execCommand('copy'); } catch (e) { }

    showInfo('ocrDebug');
    document.getElementById('modalTitle').textContent = "Raw OCR Output";
    document.getElementById('modalText').textContent = t; // Display raw text
}

function renderFlightSelection(flights, pairingId) {
    const modal = document.getElementById('flightModal');
    const list = document.getElementById('flightList');
    document.getElementById('foundPairingId').textContent = pairingId;
    document.getElementById('flightCount').innerHTML = `${flights.length} <button onclick="showRawOcr()" class="ml-2 text-[10px] text-blue-500 underline">(View Raw Text)</button>`; // Add debug link

    // Sort flights: Today's date first?
    const d = new Date();
    // Create US formatted date string MM/DD/YY to match typical parsing
    // Actually, converting to comparable is safer.
    // Let's just create a score.
    const todayStr = d.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: '2-digit' }); // MM/DD/YY

    // Sort: Matches today moves to top
    flights.sort((a, b) => {
        if (a.date === todayStr && b.date !== todayStr) return -1;
        if (a.date !== todayStr && b.date === todayStr) return 1;
        return 0;
    });

    list.innerHTML = '';

    flights.forEach((f, idx) => {
        const item = document.createElement('div');
        // Highlighting for "Today"
        const isToday = f.date === todayStr;
        const bgClass = isToday ? "bg-blue-50 border-blue-200" : "bg-white border-gray-200";

        item.className = `p-3 rounded border ${bgClass} hover:border-[#005DAA] cursor-pointer transition-colors flex justify-between items-center group`;
        item.innerHTML = `
            <div>
                <div class="flex items-center gap-2 mb-1">
                    <span class="font-bold text-[#002244] text-xs">UA ${f.flt}</span>
                    <span class="text-[10px] bg-gray-100 px-1.5 py-0.5 rounded text-gray-600 font-mono">${f.date}</span>
                    ${isToday ? '<span class="text-[9px] bg-green-100 text-green-700 px-1 rounded font-bold">TODAY</span>' : ''}
                </div>
                <div class="flex items-center gap-1 text-xs">
                    <span class="font-bold w-8">${f.depAir}</span>
                    <i class="fa-solid fa-arrow-right text-gray-300 text-[10px]"></i>
                    <span class="font-bold w-8 text-right">${f.arrAir}</span>
                    <span class="ml-2 font-mono text-gray-500">Dep: ${f.depTime}</span>
                </div>
            </div>
            <i class="fa-solid fa-chevron-right text-gray-300 group-hover:text-[#005DAA]"></i>
        `;
        item.onclick = () => selectFlight(idx);
        list.appendChild(item);
    });

    modal.classList.remove('hidden');
}

function selectFlight(idx) {
    if (!window.parsedFlights || !window.parsedFlights[idx]) {
        console.error("Flight data missing");
        return;
    }
    const f = window.parsedFlights[idx];
    console.log("Selected flight: ", f);

    // Populate Fields
    // Force Home Base setting
    const hbSelect = document.getElementById('homeBase');

    // HOME BASE LOGIC:
    // 1. Try f.homeBase (from pairing)
    // 2. If DEN (default) or invalid, try f.depAir (first flight origin) if it exists in list?
    // Actually, usually the crew starts at their home base on the first flight.

    let baseToSet = f.homeBase;

    // If baseToSet is "DEN" (default) but the Departure Airport is in the base list, use that instead?
    // (Assuming simple pairings where first leg is from base)
    // Only verify if we are sure "DEN" wasn't explicitly parsed.
    // The parser defaults to DEN if no pairing match.
    // Let's rely on pairing FIRST.

    // Check if baseToSet is valid in dropdown
    if (baseToSet && hbSelect.querySelector(`option[value="${baseToSet}"]`)) {
        hbSelect.value = baseToSet;
    } else {
        // Fallback: If pairing parsing failed, maybe user is based in the Departure city?
        // E.g. Dep "SFO". Is SFO in BASES?
        if (f.depAir && hbSelect.querySelector(`option[value="${f.depAir}"]`)) {
            hbSelect.value = f.depAir;
        } else {
            // Fallback default
            hbSelect.value = "DEN";
        }
    }

    // Airports
    document.getElementById('reportAirport').value = f.depAir !== "???" ? f.depAir : "";
    document.getElementById('depAirport').value = f.depAir !== "???" ? f.depAir : "";

    // --- NEW: Auto-Select Mode (Dom/Int) ---
    autoSelectMode(f.depAir, f.arrAir);

    // Report Time (From DP Header)
    if (f.reportTime) {
        document.getElementById('reportTime').value = f.reportTime.replace(':', '');
    }

    // Flight Time (Duration)
    // Use PASSED block time if available, otherwise blank.
    if (f.blockTime && f.blockTime.length >= 4) {
        document.getElementById('flightTimeInput').value = f.blockTime;
    } else {
        document.getElementById('flightTimeInput').value = "";
    }

    const ftInput = document.getElementById('flightTimeInput');
    // ftInput.value already set above.

    // IMPORTANT: Reset valid flags
    validateAirport(document.getElementById('reportAirport'));
    validateAirport(document.getElementById('depAirport'));

    // Set Date
    if (f.date && f.date.includes('/')) {
        const parts = f.date.split('/');
        if (parts.length >= 3) {
            const m = parts[0].padStart(2, '0');
            const d = parts[1].padStart(2, '0');
            const y = "20" + parts[2];
            document.getElementById('dutyDate').value = `${y}-${m}-${d}`;
        }
    }

    document.getElementById('flightModal').classList.add('hidden');

    // Force triggering validation
    updateAllLabels();

    // Recalculate if possible (only if flight time exists)
    if (calculatedDuration) {
        // We need to trigger the format/pad logic just in case?
        // No, value is already formatted "HH:MM".
    }
}


// --- INIT ---

function checkTestTrigger() {
    const city = document.getElementById('reportAirport').value.toUpperCase();
    validateAirport(document.getElementById('reportAirport'));
}

function init() {
    const d = new Date();
    const denverDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Denver', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
    document.getElementById('dutyDate').value = denverDate;
    const bs = document.getElementById('homeBase');
    bs.innerHTML = '';
    BASES.sort((a, b) => a.c.localeCompare(b.c)).forEach(b => { const o = document.createElement('option'); o.value = b.c; o.text = `${b.c} Pairing`; if (b.c === 'DEN') o.selected = true; bs.appendChild(o); });
    const dl = document.getElementById('airportList');
    dl.innerHTML = '';
    Object.keys(ALL_CODES).sort().forEach(c => { const o = document.createElement('option'); o.value = c; dl.appendChild(o); });

    const pZ = (id) => {
        const s = document.getElementById(id);
        s.innerHTML = '<option value="" disabled selected>Select Zone</option>';
        Object.keys(MANUAL_ZONES).forEach(group => {
            const grp = document.createElement('optgroup');
            grp.label = group;
            MANUAL_ZONES[group].forEach(z => {
                const o = document.createElement('option');
                o.value = z.val;
                o.text = z.name;
                o.dataset.short = z.short;
                grp.appendChild(o);
            });
            s.appendChild(grp);
        });
    };
    pZ('repManualZone'); pZ('depManualZone');

    document.querySelectorAll('.toggle-checkbox').forEach(chk => {
        chk.addEventListener('change', function () {
            const pillDiv = this.nextElementSibling;
            if (this.checked) {
                pillDiv.classList.add('active');
            } else {
                pillDiv.classList.remove('active');
            }
            resetResult();
            resetResult();
        });
    });

    checkCoTerminal();
    document.getElementById('reportAirport').addEventListener('input', checkTestTrigger);
    // Add flight warning listener
    const fltInput = document.getElementById('flightTimeInput');
    if (fltInput) {
        fltInput.addEventListener('input', warnFlightTime);
        // Click-away listener for popup
        document.addEventListener('click', function (e) {
            const p = document.getElementById('flightTimeWarning');
            const fltInput = document.getElementById('flightTimeInput');
            // Check if popup is visible and click is OUTSIDE the popup and OUTSIDE the input
            if (p && !p.classList.contains('hidden') && !p.contains(e.target) && e.target !== fltInput) {
                dismissFlightWarning();
            }
        });
    }

    const copyBtn = document.getElementById('btnCopyReceipt');
    if (copyBtn) { copyBtn.addEventListener('click', copyReceipt); }
    const calcBtn = document.getElementById('btnCalculate');
    if (calcBtn) { calcBtn.addEventListener('click', calculateDuty); }

    // --- NEW: Add listeners to clear errors ---
    ['dutyDate', 'homeBase', 'reportAirport', 'reportTime', 'depAirport', 'flightTimeInput'].forEach(id => {
        const el = document.getElementById(id);
        if (el) {
            el.addEventListener('input', function () {
                this.classList.remove('input-missing');
            });
            // For select elements, input might not trigger
            el.addEventListener('change', function () {
                this.classList.remove('input-missing');
            });
        }
    });

    window.nudgeZone = nudgeZone;
    window.nudgeZone = nudgeZone;
    window.calculateDuty = calculateDuty;
    window.resetForm = resetForm;
    window.toggleMode = toggleMode;
    window.toggleDarkMode = toggleDarkMode;
    window.checkCoTerminal = checkCoTerminal;
    window.toggleCoTermDropdown = toggleCoTermDropdown;
    window.validateAirport = validateAirport;
    window.formatTimeInput = formatTimeInput;
    window.padTimeInput = padTimeInput;
    window.copyReceipt = copyReceipt;
    window.showInfo = showInfo;
    window.closeInfo = closeInfo;
    window.updateAllLabels = updateAllLabels;
    window.dismissFlightWarning = dismissFlightWarning;

    // OCR Exports
    window.openScanModal = openScanModal;
    window.closeScanModal = closeScanModal;
    window.handleFileSelect = handleFileSelect;
    window.selectFlight = selectFlight;
}

window.addEventListener('DOMContentLoaded', init);
