// --- UTILITIES ---

function copyReceipt() {
    const txt = `C9 Duty Check:\nReport: ${lastCalc.rTime} ${lastCalc.rAir} (${lastCalc.hdt} ${lastCalc.hb} Time)\nScheduled FLT Time: ${lastCalc.flt}\nMax Duty: ${lastCalc.max}\nHard Stop: ${lastCalc.hardStop}\nDeductions: ${lastCalc.deducts.join(', ')}\nLATEST DOOR CLOSE: ${lastCalc.final}\n(Generated by C9 Duty Max)`;
    const ta = document.getElementById('copyArea');
    ta.value = txt;
    ta.select();
    document.execCommand('copy');
    const btn = document.querySelector('#resultCard button i');
    btn.className = "fa-solid fa-check text-green-400";
    setTimeout(() => btn.className = "fa-regular fa-copy", 1500);
}

function toggleDarkMode() {
    document.body.classList.toggle('dark-mode');
    const icon = document.getElementById('darkModeIcon');
    const text = document.getElementById('darkModeText');
    const themeMeta = document.getElementById('themeColor');

    if (document.body.classList.contains('dark-mode')) {
        icon.classList.remove('fa-moon'); icon.classList.add('fa-sun');
        text.textContent = "Light Mode";
        themeMeta.content = "#1f2937";

    } else {
        icon.classList.remove('fa-sun'); icon.classList.add('fa-moon');
        text.textContent = "Dark Mode";
        themeMeta.content = "#002244";

    }
    validateAirport(document.getElementById('reportAirport'));
    validateAirport(document.getElementById('depAirport'));
}

function toggleMode() {
    const isDom = document.getElementById('modeDom').checked;
    const hvtCheck = document.getElementById('isHVT');
    const hvtCont = document.getElementById('hvtContainer');

    if (isDom) {
        hvtCheck.disabled = false;
        hvtCont.style.opacity = "1";
    } else {
        hvtCheck.disabled = true;
        hvtCheck.checked = false;
        hvtCont.style.opacity = "0.5";
    }
    resetResult();
}

function checkCoTerminal() {
    const hb = document.getElementById('homeBase').value;
    const container = document.getElementById('coTermContainer');
    const check = document.getElementById('isCoTerm');
    check.checked = false;
    toggleCoTermDropdown();
    if (CO_TERMS[hb]) {
        container.classList.remove('hidden');
    } else {
        container.classList.add('hidden');
    }
}

function toggleCoTermDropdown() {
    const isChecked = document.getElementById('isCoTerm').checked;
    const ddCont = document.getElementById('coTermDropdownContainer');
    const dd = document.getElementById('coTermSelect');
    const hb = document.getElementById('homeBase').value;
    dd.innerHTML = '<option value="0">Select Arrival Terminal...</option>';
    if (isChecked && CO_TERMS[hb]) {
        ddCont.classList.remove('hidden');
        Object.entries(CO_TERMS[hb]).forEach(([code, mins]) => {
            const opt = document.createElement('option');
            const h = Math.floor(mins / 60);
            const m = mins % 60;
            const dur = `${h}:${m.toString().padStart(2, '0')}`;
            opt.value = mins;
            opt.text = `${code} (Surface: ${dur})`;
            dd.appendChild(opt);
        });
    } else {
        ddCont.classList.add('hidden');
    }
}

function resetResult() {
    document.getElementById('resultCard').classList.add('hidden');
    document.getElementById('errorContainer').classList.add('hidden');
    const isDom = document.getElementById('modeDom').checked;
    const prefix = isDom ? "<b class='uppercase'>DOMESTIC</b>" : "<b class='uppercase'>INTERNATIONAL</b>";
    document.getElementById('liveCalcText').innerHTML = `${prefix} Actual Max Duty = <b class="font-bold">--:--</b>. This is based on your report time of <b class="font-bold">--:--</b> (HDT).`;

}

function resetForm() {
    const d = new Date();
    const denverDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Denver', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
    document.getElementById('dutyDate').value = denverDate;
    document.getElementById('homeBase').value = 'DEN';
    ['reportAirport', 'reportTime', 'depAirport', 'flightTimeInput'].forEach(id => { const el = document.getElementById(id); el.value = ''; el.classList.remove('valid-airport', 'invalid-airport'); });
    document.querySelectorAll('.toggle-checkbox').forEach(el => { el.checked = false; el.nextElementSibling.classList.remove('active'); });
    ['repManualZone', 'depManualZone'].forEach(id => { const el = document.getElementById(id); el.classList.add('hidden'); el.value = ''; });

    ['rep', 'dep'].forEach(pfx => {
        const autoCont = document.getElementById(pfx + 'ZoneAutoContainer');
        const manCont = document.getElementById(pfx + 'ManualContainer');
        const autoInput = document.getElementById(pfx + 'ZoneAuto');
        if (autoCont && manCont) {
            autoCont.classList.remove('hidden');
            manCont.classList.add('hidden');
            autoInput.value = '--';
            autoInput.className = "info-field w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300";
            // Hide nudge buttons on reset
            const nWest = document.getElementById(pfx + 'NudgeWest');
            const nEast = document.getElementById(pfx + 'NudgeEast');
            if (nWest) nWest.classList.add('invisible');
            if (nEast) nEast.classList.add('invisible');
        }
    });

    // Explicitly reset the labels here
    const lblRep = document.getElementById('rtLabelCity');
    if (lblRep) { lblRep.textContent = "Local"; lblRep.className = ""; }


    document.getElementById('modeDom').click();
    checkCoTerminal();
    resetResult();
}

function getZone(c) { return ALL_CODES[c] ? (ZONES[ALL_CODES[c]] || ALL_CODES[c]) : null; }

function getZoneName(iana, manId) {
    if (!iana && manId) iana = document.getElementById(manId).value;
    if (!iana) return "Loc";
    try {
        const dtStr = document.getElementById('dutyDate').value;
        const dt = dtStr ? new Date(dtStr + 'T12:00:00') : new Date();
        const parts = new Intl.DateTimeFormat('en-US', { timeZone: iana, timeZoneName: 'short' }).formatToParts(dt);
        return parts.find(p => p.type === 'timeZoneName')?.value || "Loc";
    } catch (e) { return "Loc"; }
}

function padTimeInput(el) {
    let v = el.value.trim(); if (!v) return;
    v = v.replace(/\D/g, '');
    if (v.length > 2) { const i = v.length === 3 ? 1 : 2; v = v.slice(0, i) + ':' + v.slice(i); }
    const p = v.split(':');
    if (p.length === 2) el.value = `${p[0].padStart(2, '0')}:${p[1].padStart(2, '0')}`;
}

function formatTimeInput(el) {
    let v = el.value.replace(/\D/g, '');
    if (v.length > 4) v = v.slice(0, 4);
    if (v.length > 2) { const i = v.length === 3 ? 1 : 2; v = v.slice(0, i) + ':' + v.slice(i); }
    el.value = v;
}

function nudgeZone(pfx, dir) {
    const sel = document.getElementById(pfx + 'ManualZone');
    const count = sel.options.length;
    let idx = sel.selectedIndex;
    if (idx === 0) idx = 1;
    else idx += dir;
    if (idx < 1) idx = count - 1;
    if (idx >= count) idx = 1;
    sel.selectedIndex = idx;
    sel.onchange();
}

function validateAirport(el) {
    el.value = el.value.toUpperCase();
    const code = el.value;
    const pfx = el.id === 'reportAirport' ? 'rep' : 'dep';
    const zoneAutoCont = document.getElementById(pfx + 'ZoneAutoContainer');
    const zoneManualCont = document.getElementById(pfx + 'ManualContainer');
    const zoneAuto = document.getElementById(pfx + 'ZoneAuto');
    const nudgeWest = document.getElementById(pfx + 'NudgeWest');
    const nudgeEast = document.getElementById(pfx + 'NudgeEast');

    if (!zoneAutoCont || !zoneManualCont) return;
    const isDark = document.body.classList.contains('dark-mode');
    zoneAuto.style.pointerEvents = "none";

    if (code.length === 3) {
        if (ALL_CODES[code]) {
            el.classList.add('valid-airport');
            el.classList.remove('invalid-airport');

            // Dynamic Label Logic
            if (el.id === 'reportAirport') {
                const lbl = document.getElementById('rtLabelCity');
                if (lbl) { lbl.textContent = code; lbl.className = "dynamic-city-label font-bold"; }
            }

            const iana = getZone(code);
            const shortZone = getZoneName(iana);
            zoneAuto.value = shortZone;
            zoneAutoCont.classList.remove('hidden');
            zoneManualCont.classList.add('hidden');
            if (nudgeWest) nudgeWest.classList.add('invisible');
            if (nudgeEast) nudgeEast.classList.add('invisible');

            if (shortZone.includes('DT') || shortZone.includes('BST') || shortZone.includes('CEST') || shortZone.includes('EEST')) {
                zoneAuto.className = isDark ? "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-emerald-900/50 border border-emerald-700 text-emerald-200" : "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-emerald-100 border border-emerald-300 text-emerald-800";
            } else {
                zoneAuto.className = isDark ? "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-sky-900/50 border border-sky-700 text-sky-200" : "w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300 bg-sky-100 border border-sky-300 text-sky-800";
            }
        } else {
            el.classList.remove('valid-airport');
            el.classList.add('invalid-airport');
            // Reset labels if invalid
            if (el.id === 'reportAirport') {
                const lbl = document.getElementById('rtLabelCity');
                if (lbl) { lbl.textContent = "Local"; lbl.className = ""; }
            }
            zoneAutoCont.classList.add('hidden');
            zoneManualCont.classList.remove('hidden');
            if (nudgeWest) nudgeWest.classList.remove('invisible');
            if (nudgeEast) nudgeEast.classList.remove('invisible');
        }
    } else {
        el.classList.remove('valid-airport', 'invalid-airport');
        // Reset labels if empty/partial
        if (el.id === 'reportAirport') {
            const lbl = document.getElementById('rtLabelCity');
            if (lbl) { lbl.textContent = "Local"; lbl.className = ""; }
        }
        zoneAuto.value = "--";
        zoneAutoCont.classList.remove('hidden');
        zoneManualCont.classList.add('hidden');
        if (nudgeWest) nudgeWest.classList.add('invisible');
        if (nudgeEast) nudgeEast.classList.add('invisible');
        zoneAuto.className = "info-field w-full px-2 rounded text-xs font-bold text-center h-8 pointer-events-none transition-colors duration-300";
    }
}

function updateAllLabels() {
    if (document.getElementById('reportAirport').value) validateAirport(document.getElementById('reportAirport'));
    if (document.getElementById('depAirport').value) validateAirport(document.getElementById('depAirport'));
}

function showInfo(k) {
    const title = document.getElementById('modalTitle');
    const text = document.getElementById('modalText');
    const modal = document.getElementById('infoModal');

    if (title && text && modal && INFO_CONTENT[k]) {
        title.textContent = INFO_CONTENT[k].title;
        text.innerHTML = INFO_CONTENT[k].text;
        modal.classList.remove('hidden');
    }
}
function closeInfo() { document.getElementById('infoModal').classList.add('hidden'); }

// --- NEW: Flight Time Warning Logic ---
let flightWarningDismissed = false;

function warnFlightTime() {
    const val = document.getElementById('flightTimeInput').value;
    const popup = document.getElementById('flightTimeWarning');
    if (!popup) return;

    if (val.length > 0 && !flightWarningDismissed) {
        popup.classList.remove('hidden');
    } else {
        popup.classList.add('hidden');
    }
}

function dismissFlightWarning() {
    const popup = document.getElementById('flightTimeWarning');
    if (popup) popup.classList.add('hidden');
    flightWarningDismissed = true;
}

// --- CORE CALCULATION LOGIC ---

function getDateInZone(dateStr, timeStr, ianaZone) {
    const cleanTime = timeStr.replace(':', '').padStart(4, '0');
    const h = cleanTime.slice(0, 2);
    const m = cleanTime.slice(2, 4);
    const inputYear = parseInt(dateStr.split('-')[0]);
    const inputMonth = parseInt(dateStr.split('-')[1]) - 1;
    const inputDay = parseInt(dateStr.split('-')[2]);
    const inputHour = parseInt(h);
    const inputMin = parseInt(m);
    let guess = Date.UTC(inputYear, inputMonth, inputDay, inputHour, inputMin);
    for (let i = 0; i < 3; i++) {
        const parts = new Intl.DateTimeFormat('en-US', { timeZone: ianaZone, year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: false }).formatToParts(guess);
        const getP = (t) => parseInt(parts.find(p => p.type === t).value);
        const gY = getP('year'); const gM = getP('month') - 1; const gD = getP('day'); const gH = getP('hour') === 24 ? 0 : getP('hour'); const gMin = getP('minute');
        const guessTimeInZone = Date.UTC(gY, gM, gD, gH, gMin);
        const actualTarget = Date.UTC(inputYear, inputMonth, inputDay, inputHour, inputMin);
        const diff = actualTarget - guessTimeInZone;
        if (diff === 0) break;
        guess += diff;
    }
    return guess;
}

function getDynamicZoneName(utcTime, ianaZone) {
    try {
        const parts = new Intl.DateTimeFormat('en-US', { timeZone: ianaZone, timeZoneName: 'short' }).formatToParts(new Date(utcTime));
        return parts.find(p => p.type === 'timeZoneName')?.value || "Loc";
    } catch (e) { return "Loc"; }
}



let lastCalc = {};

function calculateDuty() {
    const errCont = document.getElementById('errorContainer'), errMsg = document.getElementById('errorMsg'); errCont.classList.add('hidden');

    // --- NEW: Reset Error Classes Before Checking ---
    ['dutyDate', 'homeBase', 'reportAirport', 'reportTime', 'depAirport', 'flightTimeInput'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.classList.remove('input-missing');
    });

    const req = [{ id: 'dutyDate', n: 'Duty Date' }, { id: 'homeBase', n: 'Home Base' }, { id: 'reportAirport', n: 'Report City' }, { id: 'reportTime', n: 'Report Time' }, { id: 'depAirport', n: 'Dep City' }, { id: 'flightTimeInput', n: 'Flight Time' }];

    let hasError = false;
    let firstMissing = null;

    // --- NEW: Loop to highlight ALL missing fields ---
    for (let r of req) {
        const el = document.getElementById(r.id);
        if (!el.value) {
            el.classList.add('input-missing');
            if (!firstMissing) firstMissing = r.n;
            hasError = true;
        }
    }

    if (hasError) {
        errMsg.textContent = `Missing: ${firstMissing}`;
        errCont.classList.remove('hidden');
        return;
    }

    // ... rest of logic

    const hb = document.getElementById('homeBase').value;
    const rTimeStr = document.getElementById('reportTime').value;
    let rAir = document.getElementById('reportAirport').value.toUpperCase();
    let dAir = document.getElementById('depAirport').value.toUpperCase();
    const dateStr = document.getElementById('dutyDate').value;
    const isDom = document.getElementById('modeDom').checked;

    if (rAir !== 'ZZZ') {
        if (!ALL_CODES[rAir] && document.getElementById('repManualZone').value === "") { errMsg.textContent = "Invalid Report City: Select Zone"; errCont.classList.remove('hidden'); return; }
    }
    if (!ALL_CODES[dAir] && document.getElementById('depManualZone').value === "") { errMsg.textContent = "Invalid Dep City: Select Zone"; errCont.classList.remove('hidden'); return; }

    let rZone;
    if (rAir === 'ZZZ') { rZone = getZone('DEN'); } else { rZone = ALL_CODES[rAir] ? getZone(rAir) : document.getElementById('repManualZone').value; }
    const dZone = ALL_CODES[dAir] ? getZone(dAir) : document.getElementById('depManualZone').value;
    const hZone = getZone(hb);

    const reportUTC = getDateInZone(dateStr, rTimeStr, rZone);
    const rZnStr = getDynamicZoneName(reportUTC, rZone);
    const hdtParts = new Intl.DateTimeFormat('en-US', { timeZone: hZone, hour: 'numeric', minute: 'numeric', hour12: false }).formatToParts(reportUTC);
    const hH = parseInt(hdtParts.find(p => p.type === 'hour').value) % 24; const hM = parseInt(hdtParts.find(p => p.type === 'minute').value);
    const hdtMins = hH * 60 + hM;
    const hZnStr = getDynamicZoneName(reportUTC, hZone);

    const fStr = document.getElementById('flightTimeInput').value.replace(':', '').padStart(4, '0'); const fH = parseInt(fStr.slice(0, 2)) || 0, fM = parseInt(fStr.slice(2, 4)) || 0;
    const schedFlightMins = fH * 60 + fM;
    let maxDutyMins = 0; let expl = ""; const fmt = (m) => { let h = Math.floor(m / 60), mn = m % 60; return `${h.toString().padStart(2, '0')}:${mn.toString().padStart(2, '0')}`; }

    if (isDom) {
        const isHVT = document.getElementById('isHVT').checked; const isDay = hdtMins >= 300 && hdtMins <= 1139; let limit = 13;
        expl = `13hrs (Report ${fmt(hdtMins)} HDT, 1900-0459)`;
        if (isHVT) {
            limit = 16;
            expl = `16hrs (HVT)`;
        } else {
            if (isDay) { limit = 15; expl = `15hrs (Report ${fmt(hdtMins)} HDT, 0500-1859)`; }
        }
        maxDutyMins = limit * 60;
    } else {
        if (schedFlightMins <= 480) { maxDutyMins = 16 * 60; expl = "16:00 (Int'l, Flt ≤ 8:00)"; }
        else if (schedFlightMins <= 720) { maxDutyMins = 16 * 60 + 30; expl = "16:30 (Int'l, Flt 8:01-12:00)"; }
        else { const checkIn = 75; const buffer = 210; maxDutyMins = checkIn + schedFlightMins + buffer; const debrief = document.getElementById('isDHD').checked ? 0 : 15; let cust = 0; if (document.getElementById('customsStart').checked) cust += 15; if (document.getElementById('customsEnd').checked) cust += 15; maxDutyMins += (debrief + cust); expl = "Variable (Check-in + Flt + Cust + Debr + 3:30)"; }
    }

    const debrief = document.getElementById('isDHD').checked ? 0 : 15;
    let cust = 0; if (document.getElementById('customsStart').checked) cust += 15; if (document.getElementById('customsEnd').checked) cust += 15;
    let coTermDed = 0; const isCoTerm = document.getElementById('isCoTerm').checked; if (isCoTerm && !document.getElementById('coTermContainer').classList.contains('hidden')) { coTermDed = parseInt(document.getElementById('coTermSelect').value) || 0; }
    const flightMs = schedFlightMins * 60000;
    const deductionsMs = (debrief + cust + coTermDed) * 60000;
    const maxDutyMs = maxDutyMins * 60000;
    const hardStopUTC = reportUTC + maxDutyMs;
    const doorCloseUTC = hardStopUTC - deductionsMs - flightMs;

    const timeInZone = (utc, z) => { const f = new Intl.DateTimeFormat('en-US', { timeZone: z, hour: 'numeric', minute: 'numeric', hour12: false }); const p = f.formatToParts(utc); const h = p.find(x => x.type === 'hour').value.padStart(2, '0'); const m = p.find(x => x.type === 'minute').value.padStart(2, '0'); return `${h}:${m}`; };

    const dZnStr = getDynamicZoneName(doorCloseUTC, dZone);
    const stopZnStr = getDynamicZoneName(hardStopUTC, dZone);
    const repInDepZn = getDynamicZoneName(reportUTC, dZone);
    const doorCloseStr = timeInZone(doorCloseUTC, dZone);

    document.getElementById('resultTime').textContent = doorCloseStr;
    document.getElementById('resultZone').textContent = `${dAir} Time (${dZnStr})`;

    document.getElementById('calcStepReportLocal').textContent = `${rTimeStr.replace(/(\d{2})(\d{2})/, '$1:$2')} ${rAir} (${rZnStr})`;
    document.getElementById('calcStepReportHDT').textContent = `${timeInZone(reportUTC, hZone)} ${hb} (${hZnStr})`;

    const repInDep = timeInZone(reportUTC, dZone);
    document.getElementById('calcStepReportDep').textContent = `${repInDep} ${dAir} (${repInDepZn})`;
    document.getElementById('calcStepMax').textContent = `+${fmt(maxDutyMins)}`;
    document.getElementById('calcStepMaxExplanation').textContent = expl;

    const stopLabel = document.getElementById('calcStepStopLabel');
    if (repInDepZn !== stopZnStr) {
        stopLabel.textContent = "= Duty Hard Stop (DST Adj.)";
    } else {
        stopLabel.textContent = "= Duty Hard Stop";
    }
    document.getElementById('calcStepStop').textContent = `${timeInZone(hardStopUTC, dZone)} ${dAir} (${stopZnStr})`;

    const rowCT = document.getElementById('rowCoTermLabel');
    const rowCTVal = document.getElementById('valCoTerm');
    if (coTermDed > 0) { rowCT.classList.remove('hidden'); rowCTVal.classList.remove('hidden'); rowCTVal.textContent = `-${coTermDed}`; } else { rowCT.classList.add('hidden'); rowCTVal.classList.add('hidden'); }

    document.getElementById('calcStepDebriefLabel').textContent = debrief === 0 ? "- Debrief (DHD)" : "- Debrief"; document.getElementById('calcStepDebriefVal').textContent = `-${debrief}`;

    const crL = document.getElementById('calcStepCustomsRowLabel');
    const crV = document.getElementById('calcStepCustoms');
    if (cust > 0) { crL.classList.remove('hidden'); crV.classList.remove('hidden'); crV.textContent = `-${cust}`; } else { crL.classList.add('hidden'); crV.classList.add('hidden'); }

    document.getElementById('calcStepFlight').textContent = `-${fH}:${fM.toString().padStart(2, '0')}`;
    document.getElementById('calcStepResult').textContent = `${doorCloseStr} ${dAir} (${dZnStr})`;

    const rc = document.getElementById('resultCard'); rc.classList.remove('hidden'); rc.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

    lastCalc = {
        rTime: rTimeStr.replace(/(\d{2})(\d{2})/, '$1:$2'),
        rAir: rAir, hdt: `${fmt(hdtMins)}`, hb: hb,
        flt: `${fH}:${fM.toString().padStart(2, '0')}`,
        max: expl, hardStop: `${timeInZone(hardStopUTC, dZone)} ${dAir}`,
        deducts: [],
        final: `${doorCloseStr} ${dAir}`
    };
    if (debrief > 0) lastCalc.deducts.push(`Debrief ${debrief}m`);
    if (cust > 0) lastCalc.deducts.push(`Customs ${cust}m`);
    if (coTermDed > 0) lastCalc.deducts.push(`Co-Term Travel ${coTermDed}m`);
    if (lastCalc.deducts.length === 0) lastCalc.deducts.push("None");
}

// --- INIT ---

function checkTestTrigger() {
    const city = document.getElementById('reportAirport').value.toUpperCase();
    validateAirport(document.getElementById('reportAirport'));
}

function init() {
    const d = new Date();
    const denverDate = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Denver', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
    document.getElementById('dutyDate').value = denverDate;
    const bs = document.getElementById('homeBase');
    bs.innerHTML = '';
    BASES.sort((a, b) => a.c.localeCompare(b.c)).forEach(b => { const o = document.createElement('option'); o.value = b.c; o.text = `${b.c} Pairing`; if (b.c === 'DEN') o.selected = true; bs.appendChild(o); });
    const dl = document.getElementById('airportList');
    dl.innerHTML = '';
    Object.keys(ALL_CODES).sort().forEach(c => { const o = document.createElement('option'); o.value = c; dl.appendChild(o); });

    const pZ = (id) => {
        const s = document.getElementById(id);
        s.innerHTML = '<option value="" disabled selected>Select Zone</option>';
        Object.keys(MANUAL_ZONES).forEach(group => {
            const grp = document.createElement('optgroup');
            grp.label = group;
            MANUAL_ZONES[group].forEach(z => {
                const o = document.createElement('option');
                o.value = z.val;
                o.text = z.name;
                o.dataset.short = z.short;
                grp.appendChild(o);
            });
            s.appendChild(grp);
        });
    };
    pZ('repManualZone'); pZ('depManualZone');

    document.querySelectorAll('.toggle-checkbox').forEach(chk => {
        chk.addEventListener('change', function () {
            const pillDiv = this.nextElementSibling;
            if (this.checked) {
                pillDiv.classList.add('active');
            } else {
                pillDiv.classList.remove('active');
            }
            resetResult();
            resetResult();
        });
    });

    checkCoTerminal();
    document.getElementById('reportAirport').addEventListener('input', checkTestTrigger);
    // Add flight warning listener
    const fltInput = document.getElementById('flightTimeInput');
    if (fltInput) {
        fltInput.addEventListener('input', warnFlightTime);
        // Click-away listener for popup
        document.addEventListener('click', function (e) {
            const p = document.getElementById('flightTimeWarning');
            const fltInput = document.getElementById('flightTimeInput');
            // Check if popup is visible and click is OUTSIDE the popup and OUTSIDE the input
            if (p && !p.classList.contains('hidden') && !p.contains(e.target) && e.target !== fltInput) {
                dismissFlightWarning();
            }
        });
    }

    const copyBtn = document.getElementById('btnCopyReceipt');
    if (copyBtn) { copyBtn.addEventListener('click', copyReceipt); }
    const calcBtn = document.getElementById('btnCalculate');
    if (calcBtn) { calcBtn.addEventListener('click', calculateDuty); }

    // --- NEW: Add listeners to clear errors ---
    ['dutyDate', 'homeBase', 'reportAirport', 'reportTime', 'depAirport', 'flightTimeInput'].forEach(id => {
        const el = document.getElementById(id);
        if (el) {
            el.addEventListener('input', function () {
                this.classList.remove('input-missing');
            });
            // For select elements, input might not trigger
            el.addEventListener('change', function () {
                this.classList.remove('input-missing');
            });
        }
    });

    window.nudgeZone = nudgeZone;
    window.nudgeZone = nudgeZone;
    window.calculateDuty = calculateDuty;
    window.resetForm = resetForm;
    window.toggleMode = toggleMode;
    window.toggleDarkMode = toggleDarkMode;
    window.checkCoTerminal = checkCoTerminal;
    window.toggleCoTermDropdown = toggleCoTermDropdown;
    window.validateAirport = validateAirport;
    window.formatTimeInput = formatTimeInput;
    window.padTimeInput = padTimeInput;
    window.copyReceipt = copyReceipt;
    window.showInfo = showInfo;
    window.closeInfo = closeInfo;
    window.updateAllLabels = updateAllLabels;
    window.dismissFlightWarning = dismissFlightWarning;
}

window.addEventListener('DOMContentLoaded', init);
